# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Restore all nuget packages for the solution
        run: nuget restore SampleApp.sln
      
      - name: build SampleApp solution
        run: msbuild SampleApp.sln
     
    #  - name: build SampleApp
    #    run: msbuild SampleApp
       
    #  - name: build Algorithms
    #    run: msbuild Algorithms

   #   - name: build DataStructures
   #     run: msbuild DataStructures
      
   #    - name: build SampleApp.Test
   #      run: msbuild SampleApp.Test  
      
   #   - name: build Algorithms.Test
   #     run: msbuild Algorithms.Test 
      
   #   - name: build DataStructures.Test
   #     run: msbuild DataStructures.Test

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
      
      - name: Run the Unit Tests for SampleApp
        run: vstest.console.exe SampleApp.Test\bin\Debug\SampleApp.Test.dll

      - name: Run the Unit Tests for Algorithms
        run: vstest.console.exe Algorithms.Test\bin\Debug\Algorithms.Test.dll  

      - name: Run the Unit Tests for DataStructures
        run: vstest.console.exe DataStructures.Test\bin\Debug\DataStructures.Test.dll    
